services:
  - type: web
    name: lighthouse
    env: node
    region: singapore # Choose a region close to your users
    plan: free # Using the free tier
    buildCommand: npm run install-all && cd frontend && npm run build
    startCommand: cd backend && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false # This requires manual setting in Render dashboard
      - key: SUPABASE_KEY
        sync: false # This requires manual setting in Render dashboard
    autoDeploy: true
